# Generated by Django 4.1.2 on 2022-11-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedetails',
            name='rank',
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='genre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='platform',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='plot',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='poster',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='rating1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='rating2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='review1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='review2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='similar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moviedetails',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
