# Generated by Django 4.1.2 on 2022-11-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_moviedetails_rank_moviedetails_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetails',
            name='Language',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='movie_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='rating3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='rating4',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='review3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='review4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moviedetails',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
