# Generated by Django 4.1.2 on 2022-11-25 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0004_moviedetails_language_moviedetails_movie_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedetails',
            name='similar',
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='release',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='sim_mov1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='sim_mov2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='sim_mov3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='sim_mov4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='sim_pos1',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='sim_pos2',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='sim_pos3',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='sim_pos4',
            field=models.URLField(null=True),
        ),
        migrations.CreateModel(
            name='Towatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ManyToManyField(to='members.moviedetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ManyToManyField(to='members.moviedetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
